language: objective-c

osx_image: xcode8

install:
  - brew update
  - brew upgrade carthage || true

script:
  - carthage bootstrap --platform osX
  - xcodebuild -project Up-N-Down.xcodeproj -target Up-N-Down -sdk macosx10.12

notifications:
  email: false
